### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Bogaso** [techyaura/nse-bhavcopy#2]
Hi,

I tried to run the Node.js code, however failed to achieve any result.

So far I did following:
I put entire code to index.js file, and ran that from Windows CMD as below

C:\Users\bogaso>node index.js

Error : Syntax error
Code: 800A03EA

Error report is attached
![error](https://user-images.githubusercontent.com/5356408/50632808-1931ee80-0f6f-11e9-9664-9265cce39988.png)

Any pointer how to run this correctly will be highly appreciated. Apologies if my question is too naive. Thanks,

**Comment by techyaura** [comment]
Hi @Bogaso ,

Sorry for the late response.

I have just checked on my end, its working. Could you please let me know the node version you are using?
