### ISSUE TITLE
unzip is broken due to graceful-fs@3.0.12 by unzip

### ISSUE THREAD

**Issue by imdkbj** [techyaura/nse-bhavcopy#9]
Need to change the unzip module .

ref : https://github.com/isaacs/node-graceful-fs/issues/156#event-3244290341

**Comment by techyaura** [comment]
Thanks @imdkbj for pinting the issue.
Issue have been fixed with https://github.com/techyaura/nse-bhavcopy/releases/tag/v1.0.5

**Comment by techyaura** [comment]
Issue have been fixed in version v1.05 - https://github.com/techyaura/nse-bhavcopy/releases/tag/v1.0.5

**Comment by imdkbj** [comment]
What's wrong i am doing.


![image](https://user-images.githubusercontent.com/46839821/88903145-d0d4d280-d270-11ea-9e93-16bd7ae18ce3.png)

![image](https://user-images.githubusercontent.com/46839821/88903281-12fe1400-d271-11ea-9146-079d9a054db7.png)

**Comment by techyaura** [comment]
Try cloning the latest v1.05 OR v10.6 & remove the previous NODE_MODULES folder & install the NODE_MODULES again ?
It should work now.

If still it is not working, let me know the below details -
OS ? - 
NODE VERSION?- 

I will see it, if I can reproduce on my end.
